version: '3'

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    environment:
      - http_proxy=
      - https_proxy=
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  fileserver:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./downloads:/usr/share/nginx/html
    ports:
      - "8787:80"
